name: test_documentation

on:
  push:
    branches:
      - mainline
      - releases/*

permissions:
  contents: read

jobs:
  Test-Documentation:
    name: Run Documentation Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout marqo repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: marqo

      - name: Checkout marqo-base for requirements
        uses: actions/checkout@v3
        with:
          repository: marqo-ai/marqo-base
          path: marqo-base
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r marqo-base/requirements/amd64-gpu-requirements.txt
          pip install -r marqo/requirements.dev.txt

      - name: Run Documentation Tests
        run: |
          export PYTHONPATH="./marqo/tests/integ_tests:./marqo/src:./marqo"
          pytest marqo/tests/integ_tests/test_documentation.py
